name: Deploy static site to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Sync files and set permissions
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'bash -c "
            # Ensure site folder exists
            mkdir -p /home/ubuntu/site

            # Sync contents of repo
            rsync -avz --delete /home/ubuntu/multi-tier-demo/ /home/ubuntu/site/

            # Set ownership and permissions
            sudo chown -R ubuntu:www-data /home/ubuntu/site
            sudo find /home/ubuntu/site -type d -exec chmod 755 {} \;
            sudo find /home/ubuntu/site -type f -exec chmod 644 {} \;
            sudo chmod 711 /home/ubuntu

            # Reload Nginx (config assumed already correct)
            sudo nginx -t && sudo systemctl reload nginx
          "'
